name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Install gem
      run: gem install cocoapods
    - name: Update pod
      run: (cd Example && pod update)
    - name: Install pod
      run: pod install --project-directory=Example
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build
    - name: Test
      run: set -o pipefail && xcodebuild clean build-for-testing  -enableCodeCoverage YES -workspace Example/AWAREFramework.xcworkspace -scheme AWAREFramework-Example CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -sdk iphonesimulator13.0 | xcpretty
    - name: Dry-run
      run: pod lib lint --allow-warnings
      
