name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Install gem
      run: gem install cocoapods
    - name: Update pod
      run: (cd Example && pod update)
    - name: Install pod
      run: pod install --project-directory=Example
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build
      
